### ISSUE TITLE
Updating service "mtt-saas" failed

### ISSUE THREAD

**Issue by gregorwolf** [sbarzaghialteaup/cap-multitenant-portal#1]
Hi @sbarzaghialteaup,

thank you for this great minimal example for multi-tenancy using CAP. Unfortunately the deploy fails with the error message:

> Service operation failed: Controller operation failed: 502 Updating service "mtt-saas" failed: Bad Gateway: Error creating service "mtt-saas" from offering "saas-registry" and plan "application": CF-ServiceBrokerBadResponse(10001): Service broker error: Service broker saas-registry failed with: SaaS application/service with the same appName (its value is: dev-mt-app-pub) already registered in SaaS 

That seems to be the same error that [Matthew Reddy posted](https://blogs.sap.com/2020/08/20/getting-your-head-into-cloud-application-programming-model-multitenancy/#comment-527451). I've made the adjustments that he suggested and it works after that.

Will send you a PR.

Best regards
Gregor

**Comment by sbarzaghialteaup** [comment]
Hi @gregorwolf ,

I think that the saas `appName` have to be unique in global SCP Cloud Foundry not in the single global account, maybe the Matthew suggestion works because he removed his application, can be?
I changed the xsuaa parameter `xsuaa-app` appending the ${org}.

[https://github.com/sbarzaghialteaup/cap-multitenant-portal/commit/07aed2619389a4032b4a44364f6a3c75fcf031a4](https://github.com/sbarzaghialteaup/cap-multitenant-portal/commit/07aed2619389a4032b4a44364f6a3c75fcf031a4)

Regards,
Sam
